---

- name: apply common configuration to all hosts
  hosts: all
  roles:
  - common

- name: apply configuration to ansible.homelab
  hosts: ansible.homelab
  become: yes
  handlers:
  - import_tasks: handlers/main.yml
  vars_files:
    - secrets.yml
  roles:
    - podman_init
    - ddclient
    - reddit_dns_bot
    - smokeping
