---

- name: apply common configuration to all hosts
  hosts: all
  become: yes
  roles:
  - common

- name: apply configuration to ansible.homelab
  hosts: ansible.homelab
  become: yes
  vars_files:
    - secrets.yml
  roles:
    - podman_init
    - ddclient
    - reddit_dns_bot
    - smokeping
    - freezer
    - trans
