---

- name: Mount docker nfs
  mount:
    path: /mnt/nfs/docker
    src: chu-nasty.iofq.local:/srv/docker
    fstype: nfs
    opts: auto,rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,local_lock=none
    state: mounted

- name: Mount virt nfs
  mount:
    path: /mnt/nfs/virt
    src: chu-nasty.iofq.local:/srv/virt
    fstype: nfs
    opts: auto,rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,local_lock=none
    state: mounted

