---

- name: reload_systemctl
  become: true
  systemd:
    daemon_reload: true
    scope: system
  listen: "reload_systemctl"

- name: start_service
  become: true
  systemd:
    name: "podman-{{ podman_name }}.service"
    scope: system
    state: restarted
  listen: "start_service"

- name: enable_service
  become: true
  systemd:
    name: "podman-{{ podman_name }}.service"
    scope: system
    enabled: true
  listen: "enable_service"
