---
- name: initialize server
  block:
  - name: Create swap space
    command: dd if=/dev/zero of=/swap bs=1M count=1024
    when: ansible_swaptotal_mb < 1

  - name: Make swap
    command: mkswap /swap
    when: ansible_swaptotal_mb < 1

  - name: Add swap to fstab
    action: lineinfile dest=/etc/fstab regexp="swap" line="/swap none swap sw 0 0" state=present

  - name: Turn swap on
    command: swapon -a

  - name: Set timezone to America/Chicago
    timezone:
      name: America/Chicago

  - name: Ensure group sudo exists
    group:
      name: sudo
      state: present

  - name: "add user ansible in group sudo"
    user:
      name: "ansible"
      groups: sudo

  - name: "copy sshd config"
    copy:
      src: files/sshd_config
      dest: /etc/ssh/sshd_config
      owner: root 
      group: root 
      mode: '0644'
    notify: restart sshd

  - name: "copy authorized_keys"
    copy:
      src: files/authorized_keys
      dest: /home/ansible/.ssh/authorized_keys
      owner: ansible
      group: ansible
      mode: '0644'

  - name: "copy sudoers config"
    copy:
      src: files/sudoers
      dest: /etc/sudoers
      owner: root 
      group: root 
      mode: '0440'
