---

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present
  when: ansible_distribution == "Ubuntu"

- name: template unattended-upgrades config
  template:
    src: templates/unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution == "Ubuntu"

- name: Ensure NFS common is installed.
  apt: 
    name: nfs-common 
    state: present 
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
