---

- name: ensure data mount point exists
  file:
    path: /mnt/nfs/data
    state: directory
    mode: '0755'

- name: mount docker nfs shares
  mount:
    src: raw.homelab:/srv/data
    path: /mnt/nfs/data
    opts: rw,sync,hard
    fstype: nfs
    state: mounted

- name: podman_service for {{ podman_name }}
  include_role:
    name: podman_service
