---

- name: "create systemd service file for {{ podman_name }}"
  template:
    src: templates/systemd-service.j2
    dest: /etc/systemd/system/podman-{{ podman_name }}.service
    owner: root
    group: root
    mode: 0644
  register: systemd_reg

- name: "restart service {{ podman_name }}"
  systemd:
    name: "podman-{{ podman_name }}"
    state: restarted
    daemon_reload: yes
  when: systemd_reg.changed
