---

- name: "install packages pertaining to podman"
  become: yes
  dnf:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - podman
  tags:
  - packages
